void print_last_digit(int n);
int get_digits(int n);
int get_power(void);
void print_digit(int n);
void print_digits(int n);
int print_char(char c);
int detect_negative(int n);
void print_number(int n);
void print_combination_2();
void print_combination_4();
